import { type RewardTypeOption, type Task, type TaskTypeOption } from "@/admin/types"

export const DEMO_NOW_ISO = "2026-02-15T12:00:00"
export const CLAIM_WINDOW_DAYS = 7

export const TASK_TYPE_OPTIONS: TaskTypeOption[] = [
  { value: "add_to_cart", label: "Добавить товары в корзину" },
  { value: "add_to_favorites", label: "Добавить товары в избранное" },
  { value: "purchase_amount", label: "Покупка на сумму" },
  { value: "purchase_category", label: "Покупка в категории" },
  { value: "purchase_seller", label: "Покупка у продавца" },
  { value: "visit_url", label: "Посетить URL" },
  { value: "visit_app_screen", label: "Посетить экран приложения" },
  { value: "visit_external_url", label: "Посетить сторонний URL" },
]

export const REWARD_TYPE_OPTIONS: RewardTypeOption[] = [
  { value: "bonus", label: "bonus" },
  { value: "promocode", label: "promocode" },
]

export const MOCK_TASKS: Task[] = [
  {
    id: "task_001",
    task_code: "CART_3_ITEMS_2026",
    title: "Добавить 3 товара в корзину",
    description: "Положите 3 товара в корзину и получите бонусы.",
    image_url: "",
    active_from: "2026-02-01T00:00",
    active_to: "2026-02-28T23:59",
    task_type: "add_to_cart",
    conditions: { items_count: 3 },
    purchase_period_from: null,
    purchase_period_to: null,
    reward_types: ["bonus"],
    reward_params: { bonus_amount: 300 },
    target_type: "internal_url",
    target_value: "/catalog",
    priority: 95,
    publication_state: "published",
    created_at: "2026-01-18T09:00",
    archived: false,
  },
  {
    id: "task_002",
    task_code: "FAVORITES_5_MAR",
    title: "Добавить 5 товаров в избранное",
    description: "Соберите wishlist из 5 позиций и получите промокод.",
    image_url: "",
    active_from: "2026-03-01T00:00",
    active_to: "2026-03-20T23:59",
    task_type: "add_to_favorites",
    conditions: { items_count: 5 },
    purchase_period_from: null,
    purchase_period_to: null,
    reward_types: ["promocode"],
    reward_params: {
      promocode_code: "WISHLIST-7",
      promocode_valid_to: "2026-04-15",
      promocode_terms: "Скидка 7% при заказе от 3000 ₽.",
    },
    target_type: "internal_url",
    target_value: "/favorites",
    priority: 86,
    publication_state: "published",
    created_at: "2026-02-10T14:00",
    archived: false,
  },
  {
    id: "task_003",
    task_code: "PURCHASE_5000_FEB",
    title: "Покупка от 5000 ₽",
    description: "Сделайте заказ со статусом получен на сумму от 5000 ₽.",
    image_url: "",
    active_from: "2026-02-01T00:00",
    active_to: "2026-02-10T23:59",
    task_type: "purchase_amount",
    conditions: { min_amount: 5000 },
    purchase_period_from: "2026-02-01",
    purchase_period_to: "2026-02-10",
    reward_types: ["bonus", "promocode"],
    reward_params: {
      bonus_amount: 500,
      promocode_code: "BUY5000-10",
      promocode_valid_to: "2026-03-31",
      promocode_terms: "Скидка 10% при следующем заказе от 6000 ₽.",
    },
    target_type: "internal_url",
    target_value: "/orders",
    priority: 99,
    publication_state: "published",
    created_at: "2026-01-25T12:30",
    archived: false,
  },
  {
    id: "task_004",
    task_code: "CATEGORY_ELECTRO_7K",
    title: "Покупка в категории Электроника",
    description: "Купите товары категории Электроника на сумму от 7000 ₽.",
    image_url: "",
    active_from: "2026-01-15T00:00",
    active_to: "2026-01-31T23:59",
    task_type: "purchase_category",
    conditions: { category_id: "electronics", min_amount: 7000 },
    purchase_period_from: "2026-01-15",
    purchase_period_to: "2026-01-31",
    reward_types: ["promocode"],
    reward_params: {
      promocode_code: "ELEC-12",
      promocode_valid_to: "2026-03-15",
      promocode_terms: "Скидка 12% при заказе от 6000 ₽. Не суммируется.",
    },
    target_type: "internal_url",
    target_value: "/catalog/electronics",
    priority: 91,
    publication_state: "published",
    created_at: "2026-01-10T17:00",
    archived: false,
  },
  {
    id: "task_005",
    task_code: "SELLER_SMART_INC",
    title: "Покупка у продавца Smart Inc",
    description: "Купите у продавца Smart Inc на сумму от 4000 ₽.",
    image_url: "",
    active_from: "2026-01-01T00:00",
    active_to: "2026-01-20T23:59",
    task_type: "purchase_seller",
    conditions: { seller_id: "smart-inc", min_amount: 4000 },
    purchase_period_from: "2026-01-01",
    purchase_period_to: "2026-01-20",
    reward_types: ["bonus"],
    reward_params: { bonus_amount: 400 },
    target_type: "internal_url",
    target_value: "/seller/smart-inc",
    priority: 82,
    publication_state: "published",
    created_at: "2025-12-20T11:00",
    archived: false,
  },
  {
    id: "task_006",
    task_code: "VISIT_SPRING_LANDING",
    title: "Посетить страницу весенней акции",
    description: "Откройте лендинг акции и заберите бонусы + промокод.",
    image_url: "",
    active_from: "2026-02-11T00:00",
    active_to: "2026-03-11T23:59",
    task_type: "visit_url",
    conditions: { url: "https://05.ru/spring" },
    purchase_period_from: null,
    purchase_period_to: null,
    reward_types: ["bonus", "promocode"],
    reward_params: {
      bonus_amount: 250,
      promocode_code: "SPRING-10",
      promocode_valid_to: "2026-04-01",
      promocode_terms: "Скидка 10% на выделенный ассортимент.",
    },
    target_type: "internal_url",
    target_value: "/spring",
    priority: 97,
    publication_state: "published",
    created_at: "2026-02-09T09:30",
    archived: false,
  },
  {
    id: "task_007",
    task_code: "APP_SCREEN_PROFILE",
    title: "Открыть экран профиля в приложении",
    description: "Откройте экран profile/home в приложении.",
    image_url: "",
    active_from: "2026-02-10T00:00",
    active_to: "2026-02-25T23:59",
    task_type: "visit_app_screen",
    conditions: { app_screen: "profile/home" },
    purchase_period_from: null,
    purchase_period_to: null,
    reward_types: ["bonus"],
    reward_params: { bonus_amount: 150 },
    target_type: "app_screen",
    target_value: "app://profile/home",
    priority: 89,
    publication_state: "published",
    created_at: "2026-02-08T08:00",
    archived: false,
  },
  {
    id: "task_008",
    task_code: "EXTERNAL_PARTNER_PAGE",
    title: "Посетить страницу партнера",
    description: "Откройте внешний URL партнера.",
    image_url: "",
    active_from: "2026-02-05T00:00",
    active_to: "2026-02-28T23:59",
    task_type: "visit_external_url",
    conditions: { url: "https://partner.example.com/offer" },
    purchase_period_from: null,
    purchase_period_to: null,
    reward_types: ["promocode"],
    reward_params: {
      promocode_code: "PARTNER-5",
      promocode_valid_to: "2026-03-12",
      promocode_terms: "5% на бренд-партнер. Один раз на пользователя.",
    },
    target_type: "external_url",
    target_value: "https://partner.example.com/offer",
    priority: 84,
    publication_state: "published",
    created_at: "2026-02-07T10:15",
    archived: false,
  },
  {
    id: "task_009",
    task_code: "DRAFT_CART_10",
    title: "Черновик: 10 товаров в корзину",
    description: "Черновая версия для следующего спринта.",
    image_url: "",
    active_from: "2026-03-10T00:00",
    active_to: "2026-03-31T23:59",
    task_type: "add_to_cart",
    conditions: { items_count: 10 },
    purchase_period_from: null,
    purchase_period_to: null,
    reward_types: ["bonus"],
    reward_params: { bonus_amount: 1000 },
    target_type: "internal_url",
    target_value: "/catalog",
    priority: 70,
    publication_state: "draft",
    created_at: "2026-02-14T16:20",
    archived: false,
  },
]
